version: "3"

services:

  database:
    image: "postgres:11"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero_passwd
    networks:
      - omero
    volumes:
      - "/mnt/omero/database:/var/lib/postgresql/data"

  omeroserver:
    # Build new image for OMERO server with controlled Bio-formats version, see file ./server/Dockerfile
    build:
      context: ./server
      args:
        BIOFORMATS_VERSION: 6.13.0
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero_passwd
      CONFIG_omero_db_name: omero
      ROOTPASS: omero_passwd
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "/mnt/omero/omeroserver:/OMERO"

  omeroweb:
    image: "openmicroscopy/omero-web-standalone:5.21.0"
    environment:
      OMEROHOST: omeroserver
    networks:
      - omero
    ports:
      - "4080:4080"

networks:
  omero:

volumes:
  database:
  omero:

